-- Sucatel — adiciona todos os 27 estados do Brasil (antes só tinha RJ), com
-- a capital de cada um já cadastrada como ponto de partida. Cidade e bairro
-- que a pessoa não encontrar na lista, ela mesma cadastra pelo app (mesmo
-- esquema usado pro bairro: sem coordenada até alguém revisar).

INSERT OR IGNORE INTO estados (id, nome, sigla) VALUES
 ('ac', 'Acre', 'AC'),
 ('al', 'Alagoas', 'AL'),
 ('ap', 'Amapá', 'AP'),
 ('am', 'Amazonas', 'AM'),
 ('ba', 'Bahia', 'BA'),
 ('ce', 'Ceará', 'CE'),
 ('df', 'Distrito Federal', 'DF'),
 ('es', 'Espírito Santo', 'ES'),
 ('go', 'Goiás', 'GO'),
 ('ma', 'Maranhão', 'MA'),
 ('mt', 'Mato Grosso', 'MT'),
 ('ms', 'Mato Grosso do Sul', 'MS'),
 ('mg', 'Minas Gerais', 'MG'),
 ('pa', 'Pará', 'PA'),
 ('pb', 'Paraíba', 'PB'),
 ('pr', 'Paraná', 'PR'),
 ('pe', 'Pernambuco', 'PE'),
 ('pi', 'Piauí', 'PI'),
 ('rn', 'Rio Grande do Norte', 'RN'),
 ('rs', 'Rio Grande do Sul', 'RS'),
 ('ro', 'Rondônia', 'RO'),
 ('rr', 'Roraima', 'RR'),
 ('sc', 'Santa Catarina', 'SC'),
 ('sp', 'São Paulo', 'SP'),
 ('se', 'Sergipe', 'SE'),
 ('to', 'Tocantins', 'TO');

INSERT OR IGNORE INTO cidades (id, estado_id, nome) VALUES
 ('rio-branco', 'ac', 'Rio Branco'),
 ('maceio', 'al', 'Maceió'),
 ('macapa', 'ap', 'Macapá'),
 ('manaus', 'am', 'Manaus'),
 ('salvador', 'ba', 'Salvador'),
 ('fortaleza', 'ce', 'Fortaleza'),
 ('brasilia', 'df', 'Brasília'),
 ('vitoria', 'es', 'Vitória'),
 ('goiania', 'go', 'Goiânia'),
 ('sao-luis', 'ma', 'São Luís'),
 ('cuiaba', 'mt', 'Cuiabá'),
 ('campo-grande-ms', 'ms', 'Campo Grande'),
 ('belo-horizonte', 'mg', 'Belo Horizonte'),
 ('belem', 'pa', 'Belém'),
 ('joao-pessoa', 'pb', 'João Pessoa'),
 ('curitiba', 'pr', 'Curitiba'),
 ('recife', 'pe', 'Recife'),
 ('teresina', 'pi', 'Teresina'),
 ('natal', 'rn', 'Natal'),
 ('porto-alegre', 'rs', 'Porto Alegre'),
 ('porto-velho', 'ro', 'Porto Velho'),
 ('boa-vista', 'rr', 'Boa Vista'),
 ('florianopolis', 'sc', 'Florianópolis'),
 ('sao-paulo', 'sp', 'São Paulo'),
 ('aracaju', 'se', 'Aracaju'),
 ('palmas', 'to', 'Palmas');
